import React, { useState } from 'react';
import {
  X,
  Copy,
  Check,
  Bookmark,
  BookmarkCheck,
  ThumbsUp,
  ThumbsDown,
  ExternalLink,
  AlertTriangle,
  FileText,
  Terminal,
  Clock,
  ShieldCheck,
  Share2,
  HelpCircle,
  Globe,
  Activity,
} from 'lucide-react';
import { ErrorEntry } from '../types';
import { getSymptomAreaForError, getObservedSymptomsForError } from '../utils/symptomHelper';

interface ErrorDetailModalProps {
  error: ErrorEntry | null;
  isOpen: boolean;
  onClose: () => void;
  isBookmarked: boolean;
  onToggleBookmark: (error: ErrorEntry) => void;
  onFeedback: (errorId: string, type: 'helpful' | 'unhelpful') => void;
}

export const ErrorDetailModal: React.FC<ErrorDetailModalProps> = ({
  error,
  isOpen,
  onClose,
  isBookmarked,
  onToggleBookmark,
  onFeedback,
}) => {
  const [copiedSection, setCopiedSection] = useState<string | null>(null);
  const [ticketCopied, setTicketCopied] = useState(false);
  const [feedbackSent, setFeedbackSent] = useState<'helpful' | 'unhelpful' | null>(null);

  if (!isOpen || !error) return null;

  const handleCopyText = (text: string, sectionId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedSection(sectionId);
    setTimeout(() => setCopiedSection(null), 2000);
  };

  const handleCopyTicketNote = () => {
    const formatted = `=== CYBERARK PAM INCIDENT DIAGNOSTIC ===
Error Code: ${error.code}
Component: ${error.component}
Severity: ${error.severity}
Issue Title: ${error.title}

[SYMPTOM DESCRIPTION]
${error.description}

[ROOT CAUSE ANALYSIS]
${error.cause}

[RECOMMENDED RESOLUTION STEPS]
${error.resolutionSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

[PERTINENT LOG FILES]
${error.logsToCheck?.map((l) => `- ${l}`).join('\n') || 'Check component standard logs'}

[OFFICIAL REFERENCE]
${error.sourceLinks.map((l) => `${l.title}: ${l.url}`).join('\n')}
Generated by VaultDesk PAM Ops Assistant`;

    navigator.clipboard.writeText(formatted);
    setTicketCopied(true);
    setTimeout(() => setTicketCopied(false), 2500);
  };

  const getSeverityBadge = (sev: string) => {
    switch (sev) {
      case 'Critical':
        return 'bg-[#2A1414] text-[#FF453A] border border-[#FF453A]/40 rounded-full px-2.5 py-0.5 text-xs font-semibold';
      case 'High':
        return 'bg-[#2A1414] text-[#FF6961] border border-[#FF6961]/30 rounded-full px-2.5 py-0.5 text-xs font-semibold';
      case 'Medium':
        return 'bg-[#2A1F0C] text-[#FF9F0A] border border-[#FF9F0A]/30 rounded-full px-2.5 py-0.5 text-xs font-semibold';
      case 'Low':
        return 'bg-[#12241A] text-[#30D158] border border-[#30D158]/30 rounded-full px-2.5 py-0.5 text-xs font-semibold';
      default:
        return 'bg-[#101E26] text-[#64D2FF] border border-[#64D2FF]/30 rounded-full px-2.5 py-0.5 text-xs font-semibold';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-[#05070A]/80 backdrop-blur-sm overflow-y-auto animate-in fade-in duration-150">
      <div
        id="modal-error-detail"
        className="relative w-full max-w-3xl bg-[#1A1E27] border border-[#2E3440] rounded-[20px] shadow-[0_12px_32px_rgba(0,0,0,0.55)] overflow-hidden my-8"
      >
        {/* Modal Header */}
        <div className="flex items-start justify-between p-6 border-b border-[#232833] bg-[#12151C]">
          <div className="space-y-1.5 pr-6">
            <div className="flex flex-wrap items-center gap-2">
              <span className="font-mono text-xl sm:text-2xl font-bold tracking-tight text-[#0A84FF] bg-[#1A1E27] px-2.5 py-0.5 rounded-[6px] border border-[#2E3440]">
                {error.code}
              </span>
              <span className={getSeverityBadge(error.severity)}>
                {error.severity}
              </span>
              <span className="text-xs px-2.5 py-1 rounded-[6px] font-semibold bg-[#1A1E27] text-[#A6AEC0] border border-[#2E3440]">
                {error.component}
              </span>
              {(() => {
                const saName = error.symptomArea || getSymptomAreaForError(error.code, error.component);
                return (
                  <span className="inline-flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-[6px] font-semibold bg-[#12241A] text-[#30D158] border border-[#30D158]/30">
                    <Activity className="w-3.5 h-3.5 text-[#30D158]" />
                    <span>Symptom Area: {saName}</span>
                  </span>
                );
              })()}
              {error.verifiedByCommunity && (
                <span className="inline-flex items-center gap-1 text-[11px] px-2 py-0.5 rounded-[6px] font-medium bg-[#12241A] text-[#30D158] border border-[#30D158]/30">
                  <ShieldCheck className="w-3 h-3" /> Vetted Runbook
                </span>
              )}
              {error.isCommunityResult && (
                <div
                  className="inline-flex items-center gap-1.5 text-[11px] px-2.5 py-0.5 rounded-[6px] font-semibold bg-[#101E26] text-[#64D2FF] border border-[#64D2FF]/30"
                  title="Verified CyberArk Technical Community Knowledge Base Article"
                >
                  <Globe className="w-3 h-3 text-[#64D2FF]" />
                  <span>CyberArk Community Article {error.communityArticleId ? `#${error.communityArticleId}` : ''} • Verified In-App</span>
                </div>
              )}
            </div>
            <h2 className="text-lg sm:text-xl font-bold text-[#F5F6F8] font-sans">
              {error.title}
            </h2>
          </div>

          <div className="flex items-center gap-2">
            <button
              id="btn-modal-bookmark"
              onClick={() => onToggleBookmark(error)}
              className={`p-2 rounded-[8px] border transition-colors ${
                isBookmarked
                  ? 'bg-[#12241A] border-[#30D158]/40 text-[#30D158]'
                  : 'bg-[#1A1E27] border-[#2E3440] text-[#A6AEC0] hover:text-[#F5F6F8]'
              }`}
              title={isBookmarked ? 'Remove Bookmark' : 'Bookmark this Error'}
            >
              {isBookmarked ? <BookmarkCheck className="w-5 h-5" /> : <Bookmark className="w-5 h-5" />}
            </button>
            <button
              id="btn-modal-close"
              onClick={onClose}
              className="p-2 rounded-[8px] bg-[#1A1E27] border border-[#2E3440] text-[#A6AEC0] hover:text-[#F5F6F8] hover:bg-[#232833] transition-colors"
              title="Close modal"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto">
          {/* Action Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 p-3.5 rounded-[10px] bg-[#12151C] border border-[#232833]">
            <div className="flex items-center gap-3 text-xs text-[#A6AEC0]">
              <span className="flex items-center gap-1">
                <Clock className="w-3.5 h-3.5 text-[#6E7787]" />
                Updated: {error.lastUpdated}
              </span>
              <span>•</span>
              <span>
                Affected: {error.affectedVersions.join(', ')}
              </span>
            </div>

            <button
              id="btn-copy-ticket-note"
              onClick={handleCopyTicketNote}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-[8px] bg-[#0A84FF] hover:bg-[#3B9EFF] text-white text-xs font-semibold shadow-sm transition-colors"
            >
              {ticketCopied ? (
                <>
                  <Check className="w-3.5 h-3.5" />
                  <span>Copied for ServiceNow / Jira!</span>
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy Incident Runbook</span>
                </>
              )}
            </button>
          </div>

          {/* Description & Observable Symptoms */}
          <div className="space-y-3">
            <h3 className="text-xs uppercase tracking-[0.06em] font-semibold text-[#6E7787] flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5 text-[#0A84FF]" />
              Symptom Description & Observed Failure Indicators
            </h3>
            <p className="text-sm sm:text-base text-[#F5F6F8] leading-relaxed bg-[#12151C] p-4 rounded-[10px] border border-[#232833]">
              {error.description}
            </p>

            {(() => {
              const obsList = error.observedSymptoms || getObservedSymptomsForError(error.code, error.component);
              if (!obsList || obsList.length === 0) return null;
              return (
                <div className="p-4 rounded-[10px] bg-[#080A0F] border border-[#232833] space-y-2">
                  <span className="text-[11px] font-semibold text-[#6E7787] uppercase tracking-[0.06em] flex items-center gap-1.5">
                    <Activity className="w-3 h-3 text-[#0A84FF]" />
                    Observed Failure Symptoms Checklist:
                  </span>
                  <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs text-[#A6AEC0]">
                    {obsList.map((obs, idx) => (
                      <li key={idx} className="flex items-start gap-2 bg-[#12151C] p-2.5 rounded-[8px] border border-[#232833]">
                        <span className="text-[#0A84FF] font-bold shrink-0">•</span>
                        <span>{obs}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              );
            })()}
          </div>

          {/* Root Cause */}
          <div className="space-y-2">
            <h3 className="text-xs uppercase tracking-[0.06em] font-semibold text-[#FF9F0A] flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5 text-[#FF9F0A]" />
              Root Cause Analysis (RCA)
            </h3>
            <div className="text-sm text-[#FF9F0A] bg-[#2A1F0C] border border-[#FF9F0A]/30 p-4 rounded-[10px] leading-relaxed">
              {error.cause}
            </div>
          </div>

          {/* Step-by-Step Resolution */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs uppercase tracking-[0.06em] font-semibold text-[#30D158] flex items-center gap-1.5">
                <Terminal className="w-3.5 h-3.5 text-[#30D158]" />
                Step-by-Step Remediation Procedure
              </h3>
              <span className="text-xs text-[#6E7787] font-mono">
                {error.resolutionSteps.length} Steps
              </span>
            </div>

            <ol className="space-y-2.5">
              {error.resolutionSteps.map((step, idx) => (
                <li
                  key={idx}
                  className="flex items-start gap-3 p-3.5 rounded-[10px] bg-[#080A0F] border border-[#232833] text-sm text-[#F5F6F8] group"
                >
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-[#12241A] text-[#30D158] border border-[#30D158]/40 text-xs font-semibold flex items-center justify-center mt-0.5">
                    {idx + 1}
                  </span>
                  <div className="flex-1 font-mono text-[13px] leading-relaxed">
                    {step}
                  </div>
                  <button
                    onClick={() => handleCopyText(step, `step-${idx}`)}
                    className="opacity-60 group-hover:opacity-100 p-1 hover:text-[#0A84FF] text-[#6E7787] transition-opacity"
                    title="Copy step"
                  >
                    {copiedSection === `step-${idx}` ? (
                      <Check className="w-3.5 h-3.5 text-[#30D158]" />
                    ) : (
                      <Copy className="w-3.5 h-3.5" />
                    )}
                  </button>
                </li>
              ))}
            </ol>
          </div>

          {/* Pertinent Log Files */}
          {error.logsToCheck && error.logsToCheck.length > 0 && (
            <div className="space-y-2">
              <h3 className="text-xs uppercase tracking-[0.06em] font-semibold text-[#6E7787] flex items-center gap-1.5">
                <FileText className="w-3.5 h-3.5 text-[#6E7787]" />
                Pertinent Log Files to Inspect
              </h3>
              <div className="bg-[#080A0F] p-4 rounded-[10px] border border-[#232833] space-y-1 font-mono text-xs text-[#F5F6F8]">
                {error.logsToCheck.map((log, idx) => (
                  <div key={idx} className="flex items-center justify-between py-1 border-b border-[#232833] last:border-0">
                    <span className="text-[#64D2FF]">{log}</span>
                    <button
                      onClick={() => handleCopyText(log, `log-${idx}`)}
                      className="text-[#6E7787] hover:text-[#0A84FF] text-[11px] flex items-center gap-1 ml-2 font-sans"
                    >
                      {copiedSection === `log-${idx}` ? 'Copied' : 'Copy Path'}
                    </button>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Official CyberArk Documentation & Community Verification Reference */}
          <div className="space-y-2">
            <h3 className="text-xs uppercase tracking-[0.06em] font-semibold text-[#6E7787] flex items-center gap-1.5">
              <Globe className="w-3.5 h-3.5 text-[#0A84FF]" />
              CyberArk Community Knowledge Base Reference
            </h3>
            <div className="p-4 rounded-[10px] bg-[#12151C] border border-[#232833] space-y-2">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="font-semibold text-[#64D2FF] text-xs">
                    Article #{error.communityArticleId || '000004128'}: {error.code}
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded-[4px] font-medium bg-[#12241A] text-[#30D158] border border-[#30D158]/30">
                    Full Resolution & Cause Verified In-App
                  </span>
                </div>
                {error.lastUpdated && (
                  <span className="text-[11px] text-[#6E7787]">
                    Community Validated: {error.lastUpdated}
                  </span>
                )}
              </div>
              <p className="text-[#A6AEC0] text-xs leading-relaxed">
                This troubleshooting guide and root-cause analysis is indexed from verified CyberArk Technical Community field resolutions. All remediation steps and diagnostic logs are presented directly in VaultDesk without redirecting to external portals.
              </p>
            </div>
          </div>

          {/* Tags */}
          <div className="flex flex-wrap items-center gap-1.5 pt-2">
            <span className="text-xs text-[#6E7787] mr-1">Tags:</span>
            {error.tags.map((tag) => (
              <span
                key={tag}
                className="text-[11px] px-2.5 py-0.5 rounded-[6px] bg-[#12151C] text-[#A6AEC0] border border-[#232833] font-mono"
              >
                #{tag}
              </span>
            ))}
          </div>

          {/* Feedback & Helpful Loop */}
          <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-[10px] bg-[#12151C] border border-[#232833]">
            <div className="flex items-center gap-2">
              <HelpCircle className="w-4 h-4 text-[#0A84FF]" />
              <span className="text-xs font-medium text-[#F5F6F8]">
                Did this runbook resolve your issue?
              </span>
            </div>

            <div className="flex items-center gap-2">
              <button
                id="btn-feedback-helpful"
                disabled={feedbackSent !== null}
                onClick={() => {
                  setFeedbackSent('helpful');
                  onFeedback(error.id, 'helpful');
                }}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[8px] text-xs font-semibold transition-colors ${
                  feedbackSent === 'helpful'
                    ? 'bg-[#12241A] text-[#30D158] border border-[#30D158]/40'
                    : 'bg-[#1A1E27] text-[#A6AEC0] hover:text-[#F5F6F8] border border-[#2E3440]'
                }`}
              >
                <ThumbsUp className="w-3.5 h-3.5" />
                <span>Yes ({error.helpfulCount + (feedbackSent === 'helpful' ? 1 : 0)})</span>
              </button>

              <button
                id="btn-feedback-unhelpful"
                disabled={feedbackSent !== null}
                onClick={() => {
                  setFeedbackSent('unhelpful');
                  onFeedback(error.id, 'unhelpful');
                }}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-[8px] text-xs font-semibold transition-colors ${
                  feedbackSent === 'unhelpful'
                    ? 'bg-[#2A1414] text-[#FF453A] border border-[#FF453A]/40'
                    : 'bg-[#1A1E27] text-[#A6AEC0] hover:text-[#F5F6F8] border border-[#2E3440]'
                }`}
              >
                <ThumbsDown className="w-3.5 h-3.5" />
                <span>No ({error.unhelpfulCount + (feedbackSent === 'unhelpful' ? 1 : 0)})</span>
              </button>
            </div>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-[#232833] bg-[#12151C] flex justify-end">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-[10px] bg-[#1A1E27] hover:bg-[#232833] text-[#F5F6F8] text-xs font-medium border border-[#2E3440] transition-colors"
          >
            Close Runbook
          </button>
        </div>
      </div>
    </div>
  );
};
