import { PsmWebConnector, WebFormField, WebFormAnalysisResult } from '../types';

/**
 * Format WebFormField array into authentic CyberArk PSM-WebApp WebFormFields multiline string.
 * Example format:
 * username > {Username} (searchby=id)
 * password > {Password} (searchby=id)
 * submit-button > (Button) (searchby=id)
 * main-view > (Validation) (searchby=id)
 */
export function generateCyberArkWebFormFieldsText(fields: WebFormField[]): string {
  if (!fields || fields.length === 0) {
    return '';
  }

  return fields
    .map((field) => {
      let line = `${field.target} > ${field.value}`;

      // Only append (searchby=...) if not 'id' or if explicit/xpath/name/class/css
      if (field.searchBy && field.searchBy !== 'id') {
        line += ` (searchby=${field.searchBy})`;
      } else if (field.searchBy === 'id') {
        line += ` (searchby=id)`;
      }

      return line;
    })
    .join('\n');
}

/**
 * Generate CyberArk PVWA Platform / Connection Component Configuration XML.
 */
export function generatePvwaComponentXml(connector: PsmWebConnector): string {
  const webFormFieldsText = generateCyberArkWebFormFieldsText(connector.fields);
  const escapedWebFormFields = webFormFieldsText
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

  const browserBinary =
    connector.browserType === 'Edge'
      ? 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
      : 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  CyberArk Connection Component Definition
  Generated by VaultDesk PSM Web Connector Studio
  Component ID: ${connector.connectionComponentId}
  Target URL: ${connector.targetUrl}
-->
<ConnectionComponent Id="${connector.connectionComponentId}" DisplayName="${connector.name}" FullScreen="Yes" Type="CyberArk.Extensions.Plugin.WebAppDispatcher">
  <ComponentParameters>
    <Parameter Name="TargetURL" Value="${connector.targetUrl}" Type="String" Visible="Yes" />
    <Parameter Name="BrowserPath" Value="${connector.browserPath || browserBinary}" Type="String" Visible="No" />
    <Parameter Name="ActionTimeout" Value="${connector.actionTimeout || 30}" Type="Numeric" Visible="No" />
    <Parameter Name="LockAppWindow" Value="${connector.lockAppWindow ? 'Yes' : 'No'}" Type="String" Visible="No" />
    <Parameter Name="EnforceCertificateValidation" Value="${connector.enforceCertValidation ? 'Yes' : 'No'}" Type="String" Visible="No" />
  </ComponentParameters>
  <TargetSettings Protocol="HTTP" ClientApp="&quot;C:\\Program Files (x86)\\CyberArk\\PSM\\Components\\CyberArk.Extensions.Plugin.WebAppDispatcher.exe&quot; &quot;{PSMComponentsFolder}&quot;" ClientDispatcher="" ClientURL="${connector.clientUrl || connector.targetUrl}">
    <ClientSpecific>
      <Parameter Name="RunMode" Value="${connector.runMode || 'Normal'}" />
      <Parameter Name="Browser" Value="${connector.browserType || 'Chrome'}" />
      <Parameter Name="WebFormFields" Value="${escapedWebFormFields}" />
      <Parameter Name="ActionTimeout" Value="${connector.actionTimeout || 30}" />
      <Parameter Name="EnforceCertificateValidation" Value="${connector.enforceCertValidation ? 'Yes' : 'No'}" />
      <Parameter Name="SearchBy" Value="id" />
    </ClientSpecific>
    <LockAppWindow Value="${connector.lockAppWindow ? 'Yes' : 'No'}" />
  </TargetSettings>
</ConnectionComponent>`;
}

/**
 * Generate CyberArk.Extensions.Plugin.WebAppDispatcher.exe.config
 */
export function generateDispatcherConfig(connector: PsmWebConnector): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="Browser" value="${connector.browserType}" />
    <add key="BrowserPath" value="${connector.browserPath || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'}" />
    <add key="DriverPath" value="C:\\Program Files (x86)\\CyberArk\\PSM\\Components" />
    <add key="ActionTimeout" value="${connector.actionTimeout}" />
    <add key="EnableTrace" value="yes" />
    <add key="TracePath" value="C:\\Program Files (x86)\\CyberArk\\PSM\\Logs\\Components" />
    <add key="LockAppWindow" value="${connector.lockAppWindow ? 'yes' : 'no'}" />
    <add key="EnforceCertificateValidation" value="${connector.enforceCertValidation ? 'yes' : 'no'}" />
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
</configuration>`;
}

/**
 * Validates individual WebForm field syntax and returns warning/error items.
 */
export function validateWebFormFieldSyntax(field: WebFormField): { valid: boolean; warnings: string[]; errors: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!field.target || field.target.trim() === '') {
    errors.push('Target element identifier/selector is required.');
  }

  if (!field.value || field.value.trim() === '') {
    errors.push('Action/Value expression is required.');
  }

  if (field.searchBy === 'xpath') {
    if (!field.target.startsWith('//') && !field.target.startsWith('/') && !field.target.startsWith('(')) {
      warnings.push('XPath selector usually starts with "//" or "/". Verify selector syntax.');
    }
    if (field.target.includes('"') && field.target.includes("'")) {
      warnings.push('Mixed double and single quotes in XPath may require careful escaping in PSM.');
    }
  }

  if (field.actionType === 'button' && field.value !== '(Button)' && !field.value.includes('(Button)')) {
    warnings.push('Button action type usually uses value "(Button)".');
  }

  if (field.actionType === 'click' && field.value !== '(Click)' && !field.value.includes('(Click)')) {
    warnings.push('Click action type usually uses value "(Click)".');
  }

  if (field.actionType === 'validation' && field.value !== '(Validation)' && !field.value.includes('(Validation)')) {
    warnings.push('Post-login verification step usually uses "(Validation)".');
  }

  if (field.actionType === 'wait') {
    const num = parseFloat(field.value);
    if (isNaN(num) || num <= 0) {
      errors.push('Wait step requires a positive number in seconds (e.g. 2 or 5).');
    }
  }

  return {
    valid: errors.length === 0,
    warnings,
    errors,
  };
}

/**
 * Heuristic DOM parser that analyzes raw HTML or form elements to automatically generate CyberArk WebFormFields.
 */
export function analyzeHtmlForWebForms(html: string, targetUrl: string): WebFormAnalysisResult {
  const fields: WebFormField[] = [];
  const warnings: string[] = [];

  let pageTitle = '';
  let componentName = 'Custom Web Application';
  let componentId = 'PSM-Web-CustomApp';
  let category = 'Enterprise Web Applications';

  // Try extracting host / title
  try {
    const parsed = new URL(targetUrl.startsWith('http') ? targetUrl : `https://${targetUrl}`);
    const hostClean = parsed.hostname.replace(/[^a-zA-Z0-9]/g, '');
    if (hostClean) {
      componentId = `PSM-Web-${hostClean.slice(0, 16)}`;
      componentName = `${parsed.hostname} Web Portal`;
    }
  } catch {
    // fallback
  }

  const titleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
  if (titleMatch && titleMatch[1]) {
    pageTitle = titleMatch[1].trim();
    if (pageTitle.length > 0 && pageTitle.length < 50) {
      componentName = pageTitle;
    }
  }

  // Look for inputs
  const inputRegex = /<input\b([^>]*)>/gi;
  let match;
  let hasUsername = false;
  let hasPassword = false;
  let count = 0;

  while ((match = inputRegex.exec(html)) !== null) {
    count++;
    const attrs = match[1];
    const typeMatch = attrs.match(/\btype=["']?([^"'\s>]+)/i);
    const idMatch = attrs.match(/\bid=["']?([^"'\s>]+)/i);
    const nameMatch = attrs.match(/\bname=["']?([^"'\s>]+)/i);
    const classMatch = attrs.match(/\bclass=["']?([^"'\s>]+)/i);
    const placeholderMatch = attrs.match(/\bplaceholder=["']?([^"'\s>]+)/i);

    const inputType = (typeMatch ? typeMatch[1] : 'text').toLowerCase();
    const id = idMatch ? idMatch[1] : '';
    const name = nameMatch ? nameMatch[1] : '';
    const className = classMatch ? classMatch[1] : '';
    const placeholder = placeholderMatch ? placeholderMatch[1].toLowerCase() : '';

    if (inputType === 'hidden') continue;

    // Detect Password field
    if (inputType === 'password' || name.toLowerCase().includes('pass') || id.toLowerCase().includes('pass')) {
      if (!hasPassword) {
        const selector = id || name || (className ? className.split(' ')[0] : 'input[type="password"]');
        const searchBy = id ? 'id' : name ? 'name' : className ? 'class' : 'css';
        fields.push({
          id: `gen-field-${Date.now()}-${fields.length + 1}`,
          target: selector,
          actionType: 'password',
          value: '{Password}',
          searchBy,
          comment: `Target password input element (${searchBy}=${selector})`,
        });
        hasPassword = true;
      }
      continue;
    }

    // Detect Username / Login ID field
    const isUserCandidate =
      inputType === 'email' ||
      inputType === 'text' ||
      name.toLowerCase().includes('user') ||
      name.toLowerCase().includes('login') ||
      name.toLowerCase().includes('email') ||
      id.toLowerCase().includes('user') ||
      id.toLowerCase().includes('login') ||
      id.toLowerCase().includes('email') ||
      placeholder.includes('user') ||
      placeholder.includes('email');

    if (isUserCandidate && !hasUsername) {
      const selector = id || name || (className ? className.split(' ')[0] : 'input[type="text"]');
      const searchBy = id ? 'id' : name ? 'name' : className ? 'class' : 'css';
      fields.push({
        id: `gen-field-${Date.now()}-${fields.length + 1}`,
        target: selector,
        actionType: 'username',
        value: '{Username}',
        searchBy,
        comment: `Target username/email input element (${searchBy}=${selector})`,
      });
      hasUsername = true;
      continue;
    }
  }

  // Look for Submit / Login buttons
  const buttonRegex = /<(button|input)\b([^>]*)>(.*?)(?:<\/\1>)?/gi;
  let hasSubmit = false;

  while ((match = buttonRegex.exec(html)) !== null) {
    const tag = match[1].toLowerCase();
    const attrs = match[2];
    const text = match[3] || '';

    const typeMatch = attrs.match(/\btype=["']?([^"'\s>]+)/i);
    const idMatch = attrs.match(/\bid=["']?([^"'\s>]+)/i);
    const nameMatch = attrs.match(/\bname=["']?([^"'\s>]+)/i);
    const classMatch = attrs.match(/\bclass=["']?([^"'\s>]+)/i);

    const btnType = (typeMatch ? typeMatch[1] : '').toLowerCase();
    const id = idMatch ? idMatch[1] : '';
    const name = nameMatch ? nameMatch[1] : '';
    const className = classMatch ? classMatch[1] : '';

    const isLoginBtn =
      btnType === 'submit' ||
      id.toLowerCase().includes('login') ||
      id.toLowerCase().includes('submit') ||
      id.toLowerCase().includes('signin') ||
      name.toLowerCase().includes('login') ||
      name.toLowerCase().includes('submit') ||
      text.toLowerCase().includes('log in') ||
      text.toLowerCase().includes('sign in') ||
      text.toLowerCase().includes('submit');

    if (isLoginBtn && !hasSubmit) {
      const selector = id || name || (className ? className.split(' ')[0] : `//button[@type='submit']`);
      const searchBy = id ? 'id' : name ? 'name' : className ? 'class' : 'xpath';
      fields.push({
        id: `gen-field-${Date.now()}-${fields.length + 1}`,
        target: selector,
        actionType: 'button',
        value: '(Button)',
        searchBy,
        comment: `Submit / Log in action trigger (${searchBy}=${selector})`,
      });
      hasSubmit = true;
      break;
    }
  }

  // Fallback defaults if nothing discovered
  if (fields.length === 0) {
    warnings.push('No standard HTML form elements detected automatically. Defaulted to standard CyberArk WebFormFields template.');
    fields.push(
      {
        id: `gen-field-${Date.now()}-1`,
        target: 'username',
        actionType: 'username',
        value: '{Username}',
        searchBy: 'id',
        comment: 'Default target username field (searchby=id)',
      },
      {
        id: `gen-field-${Date.now()}-2`,
        target: 'password',
        actionType: 'password',
        value: '{Password}',
        searchBy: 'id',
        comment: 'Default target password field (searchby=id)',
      },
      {
        id: `gen-field-${Date.now()}-3`,
        target: 'submit-button',
        actionType: 'button',
        value: '(Button)',
        searchBy: 'id',
        comment: 'Default submit button (searchby=id)',
      }
    );
  }

  // Always append a recommended validation step
  fields.push({
    id: `gen-field-${Date.now()}-val`,
    target: 'app-header',
    actionType: 'validation',
    value: '(Validation)',
    searchBy: 'class',
    comment: 'Post-login successful dashboard indicator (searchby=class)',
  });

  return {
    detectedUrl: targetUrl,
    pageTitle,
    formCount: count > 0 ? count : 1,
    fields,
    suggestedComponentId: componentId,
    suggestedName: componentName,
    suggestedCategory: category,
    analysisMethod: 'heuristic_parser',
    securityWarnings: warnings,
    rawHtmlSnippet: html.slice(0, 500),
  };
}
