import { PsmWebConnector, WebFormField, WebFormAnalysisResult, WebFormFieldSearchBy } from '../types';

/**
 * Format WebFormField array into authentic CyberArk PSM-WebApp WebFormFields multiline string.
 * Example format:
 * username > {Username} (searchby=id)
 * password > {Password} (searchby=id)
 * submit-button > (Button) (searchby=id)
 * main-view > (Validation) (searchby=id)
 */
export function generateCyberArkWebFormFieldsText(fields: WebFormField[]): string {
  if (!fields || fields.length === 0) {
    return '';
  }

  return fields
    .map((field) => {
      let line = `${field.target} > ${field.value}`;

      // Only append (searchby=...) if not 'id' or if explicit/xpath/name/class/css
      if (field.searchBy && field.searchBy !== 'id') {
        line += ` (searchby=${field.searchBy})`;
      } else if (field.searchBy === 'id') {
        line += ` (searchby=id)`;
      }

      return line;
    })
    .join('\n');
}

/**
 * Generate CyberArk PVWA Platform / Connection Component Configuration XML.
 */
export function generatePvwaComponentXml(connector: PsmWebConnector): string {
  const webFormFieldsText = generateCyberArkWebFormFieldsText(connector.fields);
  const escapedWebFormFields = webFormFieldsText
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

  const browserBinary =
    connector.browserType === 'Edge'
      ? 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
      : 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';

  return `<?xml version="1.0" encoding="utf-8"?>
<!--
  CyberArk Connection Component Definition
  Generated by VaultDesk PSM Web Connector Studio
  Component ID: ${connector.connectionComponentId}
  Target URL: ${connector.targetUrl}
-->
<ConnectionComponent Id="${connector.connectionComponentId}" DisplayName="${connector.name}" FullScreen="Yes" Type="CyberArk.Extensions.Plugin.WebAppDispatcher">
  <ComponentParameters>
    <Parameter Name="TargetURL" Value="${connector.targetUrl}" Type="String" Visible="Yes" />
    <Parameter Name="BrowserPath" Value="${connector.browserPath || browserBinary}" Type="String" Visible="No" />
    <Parameter Name="ActionTimeout" Value="${connector.actionTimeout || 30}" Type="Numeric" Visible="No" />
    <Parameter Name="LockAppWindow" Value="${connector.lockAppWindow ? 'Yes' : 'No'}" Type="String" Visible="No" />
    <Parameter Name="EnforceCertificateValidation" Value="${connector.enforceCertValidation ? 'Yes' : 'No'}" Type="String" Visible="No" />
  </ComponentParameters>
  <TargetSettings Protocol="HTTP" ClientApp="&quot;C:\\Program Files (x86)\\CyberArk\\PSM\\Components\\CyberArk.Extensions.Plugin.WebAppDispatcher.exe&quot; &quot;{PSMComponentsFolder}&quot;" ClientDispatcher="" ClientURL="${connector.clientUrl || connector.targetUrl}">
    <ClientSpecific>
      <Parameter Name="RunMode" Value="${connector.runMode || 'Normal'}" />
      <Parameter Name="Browser" Value="${connector.browserType || 'Chrome'}" />
      <Parameter Name="WebFormFields" Value="${escapedWebFormFields}" />
      <Parameter Name="ActionTimeout" Value="${connector.actionTimeout || 30}" />
      <Parameter Name="EnforceCertificateValidation" Value="${connector.enforceCertValidation ? 'Yes' : 'No'}" />
      <Parameter Name="SearchBy" Value="id" />
    </ClientSpecific>
    <LockAppWindow Value="${connector.lockAppWindow ? 'Yes' : 'No'}" />
  </TargetSettings>
</ConnectionComponent>`;
}

/**
 * Generate CyberArk.Extensions.Plugin.WebAppDispatcher.exe.config
 */
export function generateDispatcherConfig(connector: PsmWebConnector): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="Browser" value="${connector.browserType}" />
    <add key="BrowserPath" value="${connector.browserPath || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'}" />
    <add key="DriverPath" value="C:\\Program Files (x86)\\CyberArk\\PSM\\Components" />
    <add key="ActionTimeout" value="${connector.actionTimeout}" />
    <add key="EnableTrace" value="yes" />
    <add key="TracePath" value="C:\\Program Files (x86)\\CyberArk\\PSM\\Logs\\Components" />
    <add key="LockAppWindow" value="${connector.lockAppWindow ? 'yes' : 'no'}" />
    <add key="EnforceCertificateValidation" value="${connector.enforceCertValidation ? 'yes' : 'no'}" />
  </appSettings>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
  </startup>
</configuration>`;
}

/**
 * Validates individual WebForm field syntax and returns warning/error items.
 */
export function validateWebFormFieldSyntax(field: WebFormField): { valid: boolean; warnings: string[]; errors: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!field.target || field.target.trim() === '') {
    errors.push('Target element identifier/selector is required.');
  }

  if (!field.value || field.value.trim() === '') {
    errors.push('Action/Value expression is required.');
  }

  if (field.searchBy === 'xpath') {
    if (!field.target.startsWith('//') && !field.target.startsWith('/') && !field.target.startsWith('(')) {
      warnings.push('XPath selector usually starts with "//" or "/". Verify selector syntax.');
    }
    if (field.target.includes('"') && field.target.includes("'")) {
      warnings.push('Mixed double and single quotes in XPath may require careful escaping in PSM.');
    }
  }

  if (field.actionType === 'button' && field.value !== '(Button)' && !field.value.includes('(Button)')) {
    warnings.push('Button action type usually uses value "(Button)".');
  }

  if (field.actionType === 'click' && field.value !== '(Click)' && !field.value.includes('(Click)')) {
    warnings.push('Click action type usually uses value "(Click)".');
  }

  if (field.actionType === 'validation' && field.value !== '(Validation)' && !field.value.includes('(Validation)')) {
    warnings.push('Post-login verification step usually uses "(Validation)".');
  }

  if (field.actionType === 'wait') {
    const num = parseFloat(field.value);
    if (isNaN(num) || num <= 0) {
      errors.push('Wait step requires a positive number in seconds (e.g. 2 or 5).');
    }
  }

  return {
    valid: errors.length === 0,
    warnings,
    errors,
  };
}

/**
 * Comprehensive DOM & HTML parser that extracts real form fields from actual web pages.
 */
export function analyzeHtmlForWebForms(html: string, targetUrl: string): WebFormAnalysisResult {
  const fields: WebFormField[] = [];
  const warnings: string[] = [];

  let pageTitle = '';
  let componentName = 'Custom Web Application';
  let componentId = 'PSM-Web-CustomApp';
  let category = 'Enterprise Web Applications';

  // Try extracting host / title
  try {
    const parsed = new URL(targetUrl.startsWith('http') ? targetUrl : `https://${targetUrl}`);
    const hostParts = parsed.hostname.split('.');
    const cleanHost = hostParts.length >= 2 ? hostParts[hostParts.length - 2] : parsed.hostname;
    const hostClean = cleanHost.replace(/[^a-zA-Z0-9]/g, '');
    if (hostClean) {
      componentId = `PSM-Web-${hostClean.toUpperCase()}`;
      componentName = `${cleanHost.charAt(0).toUpperCase() + cleanHost.slice(1)} Web Portal`;
    }
  } catch {
    // fallback
  }

  const titleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
  if (titleMatch && titleMatch[1]) {
    pageTitle = titleMatch[1].trim().replace(/\s+/g, ' ');
    if (pageTitle.length > 0 && pageTitle.length < 60) {
      componentName = pageTitle;
    }
  }

  // Count forms
  const formMatches = html.match(/<form\b[^>]*>/gi) || [];
  const formCount = formMatches.length;

  // Real Input element detection
  const inputRegex = /<input\b([^>]*)>/gi;
  let match;
  let detectedInputsCount = 0;
  let hasUsername = false;
  let hasPassword = false;
  let hasOtp = false;

  interface DetectedInput {
    id: string;
    name: string;
    type: string;
    className: string;
    placeholder: string;
    ariaLabel: string;
    rawTag: string;
  }

  const parsedInputs: DetectedInput[] = [];

  while ((match = inputRegex.exec(html)) !== null) {
    detectedInputsCount++;
    const rawTag = match[0];
    const attrs = match[1];

    const typeMatch = attrs.match(/\btype=["']?([^"'\s>]+)/i);
    const idMatch = attrs.match(/\bid=["']?([^"'\s>]+)/i);
    const nameMatch = attrs.match(/\bname=["']?([^"'\s>]+)/i);
    const classMatch = attrs.match(/\bclass=["']?([^"'\s>]+)/i);
    const placeholderMatch = attrs.match(/\bplaceholder=["']?([^"'\s>]+)/i);
    const ariaMatch = attrs.match(/\baria-label=["']?([^"'\s>]+)/i);

    const inputType = (typeMatch ? typeMatch[1] : 'text').toLowerCase();
    const id = idMatch ? idMatch[1] : '';
    const name = nameMatch ? nameMatch[1] : '';
    const className = classMatch ? classMatch[1].trim() : '';
    const placeholder = placeholderMatch ? placeholderMatch[1].trim() : '';
    const ariaLabel = ariaMatch ? ariaMatch[1].trim() : '';

    if (inputType === 'hidden') continue;

    parsedInputs.push({
      id,
      name,
      type: inputType,
      className,
      placeholder,
      ariaLabel,
      rawTag,
    });
  }

  // Process parsed real inputs
  for (const input of parsedInputs) {
    const combinedStr = `${input.id} ${input.name} ${input.placeholder} ${input.ariaLabel}`.toLowerCase();

    // 1. Password input
    if (input.type === 'password' || combinedStr.includes('pass') || combinedStr.includes('pwd') || combinedStr.includes('secret')) {
      if (!hasPassword) {
        const selector = input.id || input.name || (input.className ? input.className.split(' ')[0] : 'input[type="password"]');
        const searchBy = input.id ? 'id' : input.name ? 'name' : input.className ? 'class' : 'css';

        fields.push({
          id: `real-field-pass-${fields.length + 1}`,
          target: selector,
          actionType: 'password',
          value: '{Password}',
          searchBy,
          comment: `Actual password field: <input ${input.id ? `id="${input.id}" ` : ''}${input.name ? `name="${input.name}" ` : ''}type="${input.type}" />`,
          elementSnippet: input.rawTag.slice(0, 140),
          confidence: 'high',
        });
        hasPassword = true;
      }
      continue;
    }

    // 2. MFA / OTP input
    if (combinedStr.includes('otp') || combinedStr.includes('mfa') || combinedStr.includes('token') || combinedStr.includes('code') || combinedStr.includes('totp') || combinedStr.includes('authenticator')) {
      if (!hasOtp) {
        const selector = input.id || input.name || (input.className ? input.className.split(' ')[0] : 'input[type="text"]');
        const searchBy = input.id ? 'id' : input.name ? 'name' : input.className ? 'class' : 'css';

        fields.push({
          id: `real-field-otp-${fields.length + 1}`,
          target: selector,
          actionType: 'text',
          value: '{OTP}',
          searchBy,
          comment: `MFA/OTP Authenticator Code field (${searchBy}=${selector})`,
          elementSnippet: input.rawTag.slice(0, 140),
          confidence: 'high',
          optional: true,
        });
        hasOtp = true;
      }
      continue;
    }

    // 3. Username / Email input
    const isUserCandidate =
      input.type === 'email' ||
      input.type === 'text' ||
      input.type === 'tel' ||
      combinedStr.includes('user') ||
      combinedStr.includes('login') ||
      combinedStr.includes('email') ||
      combinedStr.includes('account') ||
      combinedStr.includes('identifier') ||
      combinedStr.includes('uid') ||
      combinedStr.includes('upn') ||
      combinedStr.includes('auth') ||
      combinedStr.includes('signin') ||
      combinedStr.includes('uname');

    if (isUserCandidate && !hasUsername) {
      const selector = input.id || input.name || (input.className ? input.className.split(' ')[0] : 'input[type="text"]');
      const searchBy = input.id ? 'id' : input.name ? 'name' : input.className ? 'class' : 'css';

      fields.push({
        id: `real-field-user-${fields.length + 1}`,
        target: selector,
        actionType: 'username',
        value: '{Username}',
        searchBy,
        comment: `Actual username/email field: <input ${input.id ? `id="${input.id}" ` : ''}${input.name ? `name="${input.name}" ` : ''}type="${input.type}" />`,
        elementSnippet: input.rawTag.slice(0, 140),
        confidence: 'high',
      });
      hasUsername = true;
      continue;
    }
  }

  // If username wasn't explicitly tagged but we have a text input before password, use it
  if (!hasUsername && parsedInputs.length > 0) {
    const firstTextInput = parsedInputs.find(i => i.type === 'text' || i.type === 'email');
    if (firstTextInput) {
      const selector = firstTextInput.id || firstTextInput.name || (firstTextInput.className ? firstTextInput.className.split(' ')[0] : 'input[type="text"]');
      const searchBy = firstTextInput.id ? 'id' : firstTextInput.name ? 'name' : firstTextInput.className ? 'class' : 'css';
      fields.unshift({
        id: `real-field-user-first-${fields.length + 1}`,
        target: selector,
        actionType: 'username',
        value: '{Username}',
        searchBy,
        comment: `Primary login identifier input (${searchBy}=${selector})`,
        elementSnippet: firstTextInput.rawTag.slice(0, 140),
        confidence: 'medium',
      });
      hasUsername = true;
    }
  }

  // Real Submit / Login buttons detection
  const buttonRegex = /<(button|input)\b([^>]*)>(.*?)(?:<\/\1>)?/gi;
  let detectedButtonsCount = 0;
  let hasSubmit = false;

  while ((match = buttonRegex.exec(html)) !== null) {
    detectedButtonsCount++;
    const rawTag = match[0];
    const attrs = match[2];
    const innerText = match[3] || '';

    const typeMatch = attrs.match(/\btype=["']?([^"'\s>]+)/i);
    const idMatch = attrs.match(/\bid=["']?([^"'\s>]+)/i);
    const nameMatch = attrs.match(/\bname=["']?([^"'\s>]+)/i);
    const classMatch = attrs.match(/\bclass=["']?([^"'\s>]+)/i);
    const ariaMatch = attrs.match(/\baria-label=["']?([^"'\s>]+)/i);

    const btnType = (typeMatch ? typeMatch[1] : '').toLowerCase();
    const id = idMatch ? idMatch[1] : '';
    const name = nameMatch ? nameMatch[1] : '';
    const className = classMatch ? classMatch[1].trim() : '';
    const ariaLabel = ariaMatch ? ariaMatch[1].trim() : '';

    const combinedBtn = `${id} ${name} ${className} ${ariaLabel} ${innerText}`.toLowerCase();

    const isLoginBtn =
      btnType === 'submit' ||
      combinedBtn.includes('log in') ||
      combinedBtn.includes('login') ||
      combinedBtn.includes('sign in') ||
      combinedBtn.includes('signin') ||
      combinedBtn.includes('submit') ||
      combinedBtn.includes('continue') ||
      combinedBtn.includes('next') ||
      combinedBtn.includes('authenticate');

    if (isLoginBtn && !hasSubmit) {
      let selector = '';
      let searchBy: WebFormFieldSearchBy = 'id';

      if (id) {
        selector = id;
        searchBy = 'id';
      } else if (name) {
        selector = name;
        searchBy = 'name';
      } else if (className && !className.includes(' ')) {
        selector = className;
        searchBy = 'class';
      } else {
        selector = `//button[@type='submit' or contains(text(), 'Sign In') or contains(text(), 'Log In')]`;
        searchBy = 'xpath';
      }

      fields.push({
        id: `real-field-btn-${fields.length + 1}`,
        target: selector,
        actionType: 'button',
        value: '(Button)',
        searchBy,
        comment: `Actual submit button: <button ${id ? `id="${id}" ` : ''}${name ? `name="${name}" ` : ''}>${innerText.slice(0, 30)}</button>`,
        elementSnippet: rawTag.slice(0, 140),
        confidence: 'high',
      });
      hasSubmit = true;
      break;
    }
  }

  // Fallback defaults if site was completely empty or protected
  if (fields.length === 0) {
    warnings.push('Live page inspection found 0 standard form fields (page may require JavaScript SPA hydration). Synthesized standard CyberArk WebFormFields template.');
    fields.push(
      {
        id: `field-user-default`,
        target: 'username',
        actionType: 'username',
        value: '{Username}',
        searchBy: 'id',
        comment: 'Default target username selector (searchby=id)',
        confidence: 'medium',
      },
      {
        id: `field-pass-default`,
        target: 'password',
        actionType: 'password',
        value: '{Password}',
        searchBy: 'id',
        comment: 'Default target password selector (searchby=id)',
        confidence: 'medium',
      },
      {
        id: `field-btn-default`,
        target: 'submit-button',
        actionType: 'button',
        value: '(Button)',
        searchBy: 'id',
        comment: 'Default submit button trigger (searchby=id)',
        confidence: 'medium',
      }
    );
  }

  // Validation Rule extraction (Search for nav, header, main, user-menu in the page)
  let validationSelector = 'app-header';
  let validationSearchBy: WebFormFieldSearchBy = 'class';

  const headerMatch = html.match(/<header\b[^>]*\bid=["']?([^"'\s>]+)/i) || html.match(/<nav\b[^>]*\bid=["']?([^"'\s>]+)/i);
  if (headerMatch && headerMatch[1]) {
    validationSelector = headerMatch[1];
    validationSearchBy = 'id';
  }

  fields.push({
    id: `real-field-validation-${fields.length + 1}`,
    target: validationSelector,
    actionType: 'validation',
    value: '(Validation)',
    searchBy: validationSearchBy,
    comment: `Post-login dashboard element to confirm session validation (${validationSearchBy}=${validationSelector})`,
    confidence: 'medium',
  });

  return {
    detectedUrl: targetUrl,
    pageTitle,
    formCount: formCount > 0 ? formCount : 1,
    fields,
    suggestedComponentId: componentId,
    suggestedName: componentName,
    suggestedCategory: category,
    analysisMethod: html.length > 200 ? 'live_fetch' : 'heuristic_parser',
    securityWarnings: warnings,
    rawHtmlSnippet: html.slice(0, 1500),
    detectedInputsCount,
    detectedButtonsCount,
  };
}
